application: imified-demo
version: 1
runtime: python
api_version: 1

handlers:

- url: /assets
  static_dir: assets

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /.*
  script: main.py
  
